const products = [
  {
    id: 1,
    category: "Wireless earbuds", // must match categories.title
    img1: "img/product/home1-pro-1.jpg",
    img2: "img/product/home1-pro-2.jpg",
    subtitle: "Wireless device",
    title: "Wireless headphones",
    newPrice: "$21.00",
    oldPrice: "$25.00",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    rating: 5,
    sale: "20%",
  },
  {
    id: 2,
    category: "Portable speaker",
    img1: "img/product/home1-pro-3.jpg",
    img2: "img/product/home1-pro-4.jpg",
    subtitle: "Waterproof",
    title: "Wireless mouse",
    newPrice: "$18.00",
    oldPrice: "$24.00",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    rating: 5,
    sale: "14%",
  },
  {
    id: 3,
    category: "Air conditioner",
    img1: "img/product/home1-pro-5.jpg",
    img2: "img/product/home1-pro-6.jpg",
    subtitle: "Live program",
    title: "Pen drivess",
    newPrice: "$10.00",
    oldPrice: "$15.00",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    rating: 5,
    sale: "22%",
  },
  {
    id: 4,
    category: "Ev charging plug",
    img1: "img/product/home1-pro-7.jpg",
    img2: "img/product/home1-pro-8.jpg",
    subtitle: "Waterproof watch",
    title: "Smart watch",
    newPrice: "$32.00",
    oldPrice: "$38.00",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    rating: 5,
    sale: "30%",
  },
  {
    id: 5,
    category: "DVD player slot",
    img1: "img/product/home1-pro-1.jpg",
    img2: "img/product/home1-pro-2.jpg",
    subtitle: "Wireless device",
    title: "Wireless headphones",
    newPrice: "$21.00",
    oldPrice: "$25.00",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    rating: 5,
    sale: "20%",
  },
  {
    id: 6,
    category: "360 camera",
    img1: "img/product/home1-pro-3.jpg",
    img2: "img/product/home1-pro-4.jpg",
    subtitle: "Waterproof",
    title: "Wireless mouse",
    newPrice: "$18.00",
    oldPrice: "$24.00",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    rating: 5,
    sale: "14%",
  },
  {
    id: 7,
    category: "Wireless earbuds",
    img1: "img/product/home1-pro-5.jpg",
    img2: "img/product/home1-pro-6.jpg",
    subtitle: "Live program",
    title: "Pen drivess",
    newPrice: "$10.00",
    oldPrice: "$15.00",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    rating: 5,
    sale: "22%",
  },
  {
    id: 8,
    category: "Portable speaker",
    img1: "img/product/home1-pro-7.jpg",
    img2: "img/product/home1-pro-8.jpg",
    subtitle: "Waterproof watch",
    title: "Smart watch",
    newPrice: "$32.00",
    oldPrice: "$38.00",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
    rating: 5,
    sale: "30%",
  },
];

export default products;
